server:
  port: 8888

# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://kingsword.top:3306/translation?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: translation
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Hikari连接池配置
    hikari:
      # 最小连接
      minimum-idle: 5
      # 最大连接
      maximum-pool-size: 30
      #自动提交
      auto-commit: true
      #最大空闲时常
      idle-timeout: 30000
      #最大生命周期
      max-lifetime: 1800000
      #连接超时时间
      connection-timeout: 30000
      #心跳检测
      connection-test-query: select 1

  # 设置上传文件的最大值
  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 1500MB

logging:
  level:
    com.translation.dao: debug

hdfs:
  filePath: /program
  filePathNoProgram: /noProgram
  path: hdfs://10.32.6.221:9000
  username: hadoop

xunfei:
  url: http://raasr.xfyun.cn/api
  appId: 5d7601d6
  secretKey: 6f58f6ca2cae58dd237765e07ae63042